version: '3.8'
services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/book_over_there
    ports:
      - "8001:8001"
    env_file:
      - ./.env.dev

  postgres:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=book_db

volumes:
  postgres_data: {}
