@startuml
skin rose
skinparam classAttributeIconSize 0

title Search Book In The Club Class Diagram
class ReactComponent

class SearchBookComponent {
	+ props: Object
	+ {method} <color:red> handleSearchBook(value): book[]
}

class BookComponent {
    + props: Object
    + {method} <color:red> renderSearchBook(): SearchBookComponent
}

BookComponent --|> ReactComponent
BookComponent ..> SearchBookComponent

@enduml
