@startuml
skin rose
skinparam classAttributeIconSize 0

title Sign In Class Diagram
class ReactComponent

class UserLoginComponent {
	+ props: Object
	+ {method} <color:red> handleLogin(data: Object): void
}

class UserLoginView {
	+ serializer: UserLoginSerializer
}

class APIView {
	+ {method} <color:red> post(self, request)
}

class UserLoginSerializer {
	+ username: string
	+ password: string
	+ {method} <color:red> is_valid(): boolean
}

class UserManager {
	+ {method} <color:red> authenticate(username, password): User
	+ {method} register_user(user): void
	+ {method} get_user_record(*args, **kwargs): User
	+ {method} update_user_password(user, new_password): void
}

class UserModel
UserManager *-- UserModel

ReactComponent <|-- UserLoginComponent
APIView <|-- UserLoginView
UserLoginComponent ..> UserLoginView
UserLoginView ..> UserLoginSerializer
UserLoginView ..> UserManager
@enduml
