@startuml
skin rose
skinparam classAttributeIconSize 0

title Reset Password Class Diagram
class ReactComponent

class ResetPasswordComponent {
	+ props: Object
	+ {method} <color:red> handleResetPassword(): void
}

class APIView {
	+ {method} <color:red> post(self, request)
}

class ResetPasswordConfirmView {
	+ serializer: ResetPasswordConfirmSerializer
    - uidb64: string
    - token: string
    - {method} <color:red> decode_base64(uibd64: string): integer
}

class ResetPasswordConfirmSerializer {
    + new_password: string
    + {method} <color:red> is_valid(): boolean
}

class UserManager {
	+ {method} authenticate(username, password): User
	+ {method} register_user(user): void
	+ {method} <color:red> get_user_record(*args, **kwargs): User
    + {method} <color:red> update_user_password(user, new_password): void
}

class PasswordResetTokenGenerator {
    + key_salt: string
    + algorithm: string
    - secret: string
    + {method} make_token(user): string
    + {method} <color:red> check_token(user, token): boolean
}

class UserModel
UserManager *-- UserModel

ReactComponent <|-- ResetPasswordComponent
APIView <|-- ResetPasswordConfirmView
ResetPasswordComponent ..> ResetPasswordConfirmView
ResetPasswordConfirmView ..> ResetPasswordConfirmSerializer
ResetPasswordConfirmView ..> PasswordResetTokenGenerator
ResetPasswordConfirmView ..> UserManager
@enduml
