@startuml
title Reset Password Sequence Diagram
actor RegisterUser
activate ResetPasswordComponent
RegisterUser -> ResetPasswordComponent: Click on Reset-Password-Link,\nOpen Reset Password Screen
ResetPasswordComponent --> RegisterUser: Render Reset Password Form
RegisterUser -> ResetPasswordComponent: Input New Password and Confirm Password
activate PasswordResetView
ResetPasswordComponent -> PasswordResetView: POST `password-reset/confirm`
activate PasswordResetSerializer
PasswordResetView -> PasswordResetSerializer: is_valid()
alt valid data success
	PasswordResetSerializer -> PasswordResetView: Return validated_data
else valid data failed
   PasswordResetSerializer -> PasswordResetView: Return Error
   PasswordResetView --> ResetPasswordComponent: Response Error Message
	ResetPasswordComponent -> RegisterUser: Notify Error Message
end
deactivate PasswordResetSerializer
PasswordResetView -> PasswordResetView: decode_base64(uibd64: string)

activate UserManager
PasswordResetView -> UserManager: get_user_record(user_id=uid)

activate UserModel
UserManager -> UserModel: query()

database Database
activate Database
UserModel -> Database: SELECT query
Database -> UserModel: success
deactivate Database
UserModel -> UserManager: success
deactivate UserModel
UserManager -> PasswordResetView: Return user

activate PasswordResetTokenGenerator
PasswordResetView -> PasswordResetTokenGenerator: check_token(user, token)v
alt Valid Token
   PasswordResetTokenGenerator -> PasswordResetView: success
else Invalid Token
   PasswordResetTokenGenerator -> PasswordResetView: Error Invalid Token
   PasswordResetView --> ResetPasswordComponent: Response Error Message
   ResetPasswordComponent -> RegisterUser: Notify Error Message
end
deactivate PasswordResetTokenGenerator

PasswordResetView -> UserManager: update_user_password(user, new_password)
activate UserModel
UserManager -> UserModel: update()
activate Database
UserModel -> Database: UPDATE query
Database -> UserModel: success
deactivate Database
UserModel -> UserManager: success
deactivate UserModel
UserManager -> PasswordResetView: success
deactivate UserManager

PasswordResetView --> ResetPasswordComponent: Response Success
ResetPasswordComponent -> RegisterUser: Notify Success
@enduml
