@startuml
title Forgot Password Sequence Diagram
actor RegisterUser
activate ForgotPasswordComponent
RegisterUser -> ForgotPasswordComponent: Open Forgot Password Screen
ForgotPasswordComponent --> RegisterUser: Render Forgot Password Form
RegisterUser -> ForgotPasswordComponent: Input Username or Email
activate PasswordResetView
ForgotPasswordComponent -> PasswordResetView: POST `user/password-reset`
activate PasswordResetSerializer
PasswordResetView -> PasswordResetSerializer: validate_username_or_email(data)
alt valid data success
	PasswordResetSerializer -> PasswordResetView: Return User
else valid data failed
   PasswordResetSerializer -> PasswordResetView: Return Error
   PasswordResetView --> ForgotPasswordComponent: Response Error Message
	 ForgotPasswordComponent -> RegisterUser: Notify Error Message
end
deactivate PasswordResetSerializer
activate PasswordResetTokenGenerator
PasswordResetView -> PasswordResetTokenGenerator: make_token(user)
PasswordResetTokenGenerator -> PasswordResetView: return token
deactivate PasswordResetTokenGenerator
activate EmailManager
PasswordResetView -> EmailManager: send_password_reset_email(user.email, token)
activate Django.Core.Mail
EmailManager -> Django.Core.Mail: send_email(*args, **kwargs)
EmailManager -> PasswordResetView: success
deactivate EmailManager
PasswordResetView --> ForgotPasswordComponent: Reponse Success
ForgotPasswordComponent -> RegisterUser: Notify Success Message
deactivate PasswordResetView
deactivate ForgotPasswordComponent
Django.Core.Mail --> RegisterUser: Sent an Email to User's Email Address
deactivate Django.Core.Mail
@enduml
