@startuml
skin rose
skinparam classAttributeIconSize 0

title Forgot Password Class Diagram
class ReactComponent

class ForgotPasswordComponent {
	+ props: Object
	+ {method} <color:red> handleForgotPassword(): void
}

class APIView {
	+ {method} <color:red> post(self, request)
}

class PasswordResetView {
	+ serializer: PasswordResetSerializer
    - user: User
    - token: string
}

class PasswordResetSerializer {
    + username_or_email: string
    + {method} <color:red> validate_username_or_email(value): User
}

class UserModel
PasswordResetSerializer *-- UserModel

class PasswordResetTokenGenerator {
    + key_salt: string
    + algorithm: string
    - secret: string
    + {method} <color:red> check_token(user, token): boolean
    + {method} <color:red> make_token(user): string
}

class EmailManager {
    + {method} <color:red> send_password_reset_email(email: string, token: string): void
}

class Django.Core.Mail {
    + {method} <color:red> send_mail(subject, message, from_email, recipient_list): void
}

ReactComponent <|-- ForgotPasswordComponent
APIView <|-- PasswordResetView
ForgotPasswordComponent ..> PasswordResetView
PasswordResetView ..> PasswordResetSerializer
PasswordResetView ..> PasswordResetTokenGenerator
PasswordResetView ..> EmailManager
Django.Core.Mail <|-- EmailManager
@enduml
