@startuml
skin rose 
skinparam ClassAttributeIconSize 0

title View Personal Profile Class Diagram 

class ReactComponent

class UserInfoComponent{
    + props: Object 
    + {method} <color:red> handleUserInfoView(): void 
}

class UserInfoView {
    + serializer: UserSerializer
}

class APIView {
    + {method} <color:red> post(self, request)
}

class UserSerializer {
    + phone_number: String 
    + email: String 
    + address: String 
    + full_name: String 
    + birth_date: Date 
    + avatar: File 
}

class UserManager {
    + {method}<color:red> view_userInfo(): user
}

class UserModel 

ReactComponent <|-- UserInfoComponent
APIView <|-- UserInfoView
UserInfoComponent ..>UserInfoView
UserInfoView ..> UserSerializer
UserInfoView ..> UserManager
UserManager *-- UserModel
@enduml


