@startuml
skin rose 
skinparam ClassAttributeIconSize 0

title Change Avatar Class Diagram 

class ReactComponent

class ChangeAvatarComponent {
    + props: Object 
    + {method} <color:red> handleUserUpdateView(): void 
}

class UpdateUserInfoView {
    + permission_classes: IsAuthenticated
    + serializer: UserUpdateSerializer
}

class APIView {
    + {method} <color:red> post(self, request)
}

class ChangeAvatarSerializer {
    + avatar: File 
    + {method} <color:red> is_verify(): boolean
}

class UserManager {
    + {method} <color:red> update_user(avatar): void
}

class FileManager {
    + {method} <color:red> upload_file(file): string
}

class UserModel {
    + avatar: FileStorage
}

ReactComponent <|-- ChangeAvatarComponent
APIView <|-- UpdateUserInfoView
ChangeAvatarComponent ..> UpdateUserInfoView
UpdateUserInfoView ..> ChangeAvatarSerializer
UpdateUserInfoView ..> UserManager
UserManager ..> FileManager
UserManager *-- UserModel

@enduml