@startuml
actor Member
activate OrderBorrowBookComponent
Member -> OrderBorrowBookComponent: Open Order Borrow Screen
OrderBorrowBookComponent --> Member: Render Order Borrow Book
activate SearchOrderBorrowComponent
OrderBorrowBookComponent -> SearchOrderBorrowComponent: renderSearchOrderBorrowBook()
SearchOrderBorrowComponent --> Member: Render Search Order Borrow Book Form
Member -> SearchOrderBorrowComponent: Input Book Name to Search
SearchOrderBorrowComponent -> SearchOrderBorrowComponent: handleSearch(value)
SearchOrderBorrowComponent --> OrderBorrowBookComponent: Re-render New Order Borrow Book List
deactivate SearchOrderBorrowComponent
OrderBorrowBookComponent --> Member: Show Order Borrow Book after Search 
deactivate OrderBorrowBookComponent
@enduml