@startuml
skin rose
skinparam classAttributeIconSize 0

title Search Order Borrow Book Class Diagram
class ReactComponent

class SearchOrderBorrowBookComponent {
	+ props: Object
	+ {method} <color:red> handleSearchOrderBorrowBook(data: Object): void
}

class SearchOrderBorrowBookView {
	+ serializer: SearchOrderBorrowBookSerializer
}

class APIView {
	+ {method} <color:red> post(self, request)
}
class SearchOrderBorrowBookSerializer {
	+ id: bigint
    + return_date: datetime
    + overdue_day_count: int
	+ order_id: bigint
	+ club_book_id: bigint
	+ note: string
	+ order_status: string
	+ {method} <color:red> is_valid(): boolean
}
class OrderManager{
    + {method} <color:red> get_order_record(data): List order
}
class OrderDetailModel{

}
class OrderModel{

}
ReactComponent <|-- SearchOrderBorrowBookComponent
APIView <|-- SearchOrderBorrowBookView
SearchOrderBorrowBookComponent ..> SearchOrderBorrowBookView
SearchOrderBorrowBookView ..> SearchOrderBorrowBookSerializer
SearchOrderBorrowBookView ..> OrderManager
OrderManager *-- OrderModel
 
OrderModel "1" *-- "many" OrderDetailModel : contains
@enduml