@startuml
skin rose
skinparam classAttributeIconSize 0

title Filter Order Borrow Book Class Diagram
class ReactComponent

class FilterOrderBorrowBookComponent {
	+ props: Object
	+ {method} <color:red> handleFilterOrderByMember(data: Object): void
}

class FilterOrderBorrowBookView {
	+ serializer: FilterOrderBorrowBookSerializer
}

class APIView {
	+ {method} <color:red> post(self, request)
}
class FilterOrderBorrowBookSerializer {
    + id: bigint
    + full_name: string
    + phone_number: string
    + address: string
    + order_date: datetime
    + due_date: datetime 
    + club_id: bigint
    + user_id: bigint
    + club_book_ids: bigint
    + draft_status: string
    + {method} <color:red> is_valid(): boolean
}
class OrderManager{
    + {method} <color:red> get_order_record(data): List order
}
class OrderDetailModel{

}
ReactComponent <|-- FilterOrderBorrowBookComponent
APIView <|-- FilterOrderBorrowBookView
FilterOrderBorrowBookComponent ..> FilterOrderBorrowBookView
FilterOrderBorrowBookView ..> FilterOrderBorrowBookSerializer
FilterOrderBorrowBookView ..> OrderManager
OrderManager *-- OrderModel
OrderModel "1" *-- "many" OrderDetailModel : contains
@enduml