@startuml

skin rose
skinparam classAttributeIconSize 0

title Approve Join Club Request Class Diagram
class ReactComponent

class ApproveJoinClubRequestComponent {
	+ props: Object
	+ {method} <color:red> handleApproveJoinClubRequest(data: Object): void
}
class ApproveJoinClubRequestView {
  + serializer: BookClubRequestToJoinSerializer
}
class APIView {
	+ {method} <color:red> post(self, request)
}
class ApproveJoinClubRequestSerializer {
  + user_id: bigint
  + book_clubs: bigint
  + full_name: string
  + birth_date: datetime 
  + email: string
  + phone_number: string
  + address: string
  + {method} <color:red> is_valid()
}
class ClubManager{
  + {method} <color:red> approve_member(data): Member
}
class MemberModel{

}
ReactComponent <|-- ApproveJoinClubRequestComponent
APIView <|-- ApproveJoinClubRequestView
ApproveJoinClubRequestComponent ..> ApproveJoinClubRequestView
ApproveJoinClubRequestView ..> ApproveJoinClubRequestSerializer
ApproveJoinClubRequestView ..> ClubManager
ClubManager *-- MemberModel

MemberModel "1" *-- "many" MemberShipModel : contains
@enduml
