@startuml
skin rose
skinparam classAttributeIconSize 0

title Add New Member Class Diagram
class ReactComponent

class AddNewMemberComponent {
	+ props: Object
	+ {method} <color:red> handleCreateMember(data: Object): void
}

class AddNewMemberView {
	+ serializer: AddNewMemberSerializer
}

class APIView {
	+ {method} <color:red> post(self, request)
}

class AddNewMemberSerializer {
	  + user_id: bigint
    + book_clubs: bigint
    + full_name: string
    + birth_date: datetime 
    + email: string
    + phone_number: string
    + address: string
	+ {method} <color:red> is_valid(): boolean
}

class MemberManager {
  + {method} <color:red> add_new_member(data): Member
}

class MemberModel {
}

ReactComponent <|-- AddNewMemberComponent
APIView <|-- AddNewMemberView
AddNewMemberComponent ..> AddNewMemberView
AddNewMemberView ..> AddNewMemberSerializer
AddNewMemberView ..> MemberManager
MemberManager *-- MemberModel

@enduml