@startuml
skin rose
skinparam classAttributeIconSize 0

title Update Member Class Diagram
class ReactComponent

class UpdateMemberComponent {
	+ props: Object
	+ {method} <color:red> handleUpdateMember(data: Object): void
}

class UpdateMemberView {
	+ serializer: UpdateMemberSerializer
}

class APIView {
	+ {method} <color:red> post(self, request)
}

class UpdateMemberSerializer {
	+ user_id: bigint
    + book_clubs: bigint
    + full_name: string
    + birth_date: datetime 
    + email: string
    + phone_number: string
    + address: string
	+ {method} <color:red> is_valid(): boolean
}

class MemberManager {
  +  {method} <color:red> get_member(data): Member
  +  {method} <color:red> update_member(data): Member
}

class MemberModel {
}

ReactComponent <|-- UpdateMemberComponent
APIView <|-- UpdateMemberView
UpdateMemberComponent ..> UpdateMemberView
UpdateMemberView ..> UpdateMemberSerializer
UpdateMemberView ..> MemberManager
MemberManager *-- MemberModel

@enduml