@startuml
skin rose
skinparam classAttributeIconSize 0

title Search Member Class Diagram
class ReactComponent

class SearchMemberComponent {
	+ props: Object
	+ {method} <color:red> handleSearchMember(data: Object): void
}

class SearchMemberView {
	+ serializer: SearchMemberSerializer
}

class APIView {
	+ {method} <color:red> post(self, request)
}
class SearchMemberSerializer {
	+ user_id: bigint
    + book_clubs: bigint
    + full_name: string
    + birth_date: datetime 
    + email: string
    + phone_number: string
    + address: string
	+ {method} <color:red> is_valid(): boolean
}

class MemberManager {
  + {method} <color:red> get_member_record(data): Member
  + {method} <color:red> get_member_infos(data): Member
}

class MemberModel {
}

ReactComponent <|-- SearchMemberComponent
APIView <|-- SearchMemberView
SearchMemberComponent ..> SearchMemberView
SearchMemberView ..> SearchMemberSerializer
SearchMemberView ..> MemberManager
MemberManager *-- MemberModel

@enduml