@startuml
skin rose
skinparam classAttributeIconSize 0

title View List Orders Class Diagram
class ReactComponent

class StaffViewOrderListComponent {
	+ props: Object
	+ {method} <color:red> handleViewListOrderBorrow(data: Object): void
}

class OrderGetIdsView {
	+ serializer: GetOrderIdsSerializer
}

class GetOrderInfosView {
	+ serializer: GetOrderIdsSerializer
}

class APIView {
	+ {method} <color:red> post(self, request)
}

class GetOrderInfosSerializer {
	+  order_ids: list
	+ {method} <color:red> is_valid(): boolean
}

class GetOrderIdsSerializer {
	+  club_id: interger
	+  from_date: date
	+  to_date: date
	+  order_date: date
	+  order_status: integer
	+  order_month: date
	+  Staff: integer
	+ {method} <color:red> is_valid(): boolean
}
class OrderManager {
	+ {method} <color:red> get_order_infos(order_ids): List Order
	+ {method} <color:red> get_order_ids(data): List integer
}

class OrderModel {
}
class OrderDetailModel {
}

ReactComponent <|-- StaffViewOrderListComponent
APIView <|-- OrderGetIdsView
APIView <|-- GetOrderInfosView
StaffViewOrderListComponent ..> OrderGetIdsView
StaffViewOrderListComponent ..> GetOrderInfosView
GetOrderInfosView ..> GetOrderInfosSerializer
GetOrderInfosView ..> OrderManager
OrderGetIdsView ..> GetOrderIdsSerializer
OrderGetIdsView ..> OrderManager
OrderManager *-- OrderModel
OrderModel "1" *-- "many" OrderDetailModel : contains
@enduml
