@startumlMember
skin rose
skinparam classAttributeIconSize 0

title Filter Order By Created Date Class Diagram
class ReactComponent

class FilterOrderByCreatedDateComponent {
	+ props: Object
	+ {method} <color:red> handleFilterOrderByCreatedDate(data: Object): void
}

class FilterOrderByCreatedDateView {
	+ serializer: FilterOrderByCreatedDateSerializer
}

class APIView {
	+ {method} <color:red> post(self, request)
}

class FilterOrderByCreatedDateSerializer {
	+  createdDate: date
	+ {method} <color:red> is_valid(): boolean
}

class OrderManager {
	+ {method} <color:red> get_order_records(createdDate): listOrder
}

class OrderModel {
}
class OrderDetailModel {
}
ReactComponent <|-- FilterOrderByCreatedDateComponent
APIView <|-- FilterOrderByCreatedDateView
FilterOrderByCreatedDateComponent ..> FilterOrderByCreatedDateView
FilterOrderByCreatedDateView ..> FilterOrderByCreatedDateSerializer
FilterOrderByCreatedDateView ..> OrderManager
OrderManager *-- OrderModel
OrderModel "1" *-- "many" OrderDetailModel : contains
@enduml
