@startuml Filter Order By Phone Number Sequence Diagram 
title Filter Order By Phone Number Sequence Diagram 

actor ClubStaff 

activate OrderComponent
ClubStaff -> OrderComponent: Open Orrder List Screen

activate OrderView
OrderComponent -> OrderFilterView: POST `Order/list`
activate OrderManager
deactivate OrderFilterView
OrderFilterView -> OrderManager: get_orders(phone)
activate OrderModel
OrderManager -> OrderModel: querry_orders()

database Database
activate Database
OrderModel -> Database: SELECT Querry

Database -> OrderModel: Return data
deactivate Database
deactivate OrderModel
OrderModel -> OrderManager: Return orders


OrderManager -> OrderFilterView: Return orders
deactivate OrderManager
activate OrderSerializer
OrderFilterView -> OrderSerializer: to_representation(instance=Orders, many=true)

OrderSerializer -> OrderFilterView: Return response_data
deactivate OrderSerializer
OrderFilterView --> OrderComponent: Return list Orders Data
OrderComponent -> ClubStaff: Show Orders Information
deactivate OrderComponent



