@startuml
skin rose
skinparam classAttributeIconSize 0

title Create Order Class Diagram
class ReactComponent

class CreateNewOrderComponent {
	+ props: Object
	+ {method} <color:red> handleCreateNewOrderForNewMember(data: Object): void
	+ {method} <color:red> handleCreateNewOrderForOldMember(data: Object): void
}

class OrderCreateView {
	+ serializer: OrderCreateNewMemberSerializer
	+ serializer: OrderCreateSerializer
}

class OrderCreateSerializer {
    - member_id: ListInteger
	- order_date: datetime `
}
class APIView {
	+ {method} <color:red> post(self, request)
}

class OrderCreateNewMemberSerializer {
    - member_id: ListInteger
	- order_date: datetime `
}

class MembershipManager {
	+ {method} <color:red> : get_membership_records(user, is_staff, membership_id, club_id): club_ids
	+ {method} <color:red> : validate_member(club_id, code, phone_number, club_ids): boolean, error
}

class OrderManager {
	+ {method} <color:red> : create_new_order_by_new_member(data): order
	+ {method} <color:red> : create_new_order(data): order
}

class OrderModel 
class OrderDetaiModel
class MemberModel
class MemberDetailModel

ReactComponent <|-- CreateNewOrderComponent
APIView <|-- OrderCreateView
CreateNewOrderComponent ..> OrderCreateView
OrderCreateView ..> OrderCreateNewMemberSerializer
OrderCreateView ..> OrderManager
OrderCreateView ..> MembershipManager
OrderManager *-- OrderModel
MembershipManager *-- MemberModel
OrderDetaiModel "many" --* "1"OrderModel :contain
MemberDetailModel "many" --* "1"MemberModel :contain
@enduml
