@startuml
skin rose
skinparam classAttributeIconSize 0

title Search Club Class Diagram

class ReactComponent

class ClubComponent{
    + props: Object
    + {method} <color:red> handleViewCLub(data: Object):void
}

