@startuml
skin rose
skinparam classAttributeIconSize 0

title Search Book In The Club Class Diagram
class ReactComponent

class BookClubListComponent {
	+ props: Object
	+ {method} <color:red> get_club_book_list(club_book_ids): book
}

class ClubBookListAPIView {
	+ serializer: BookSerializer
    + name: string
}

class APIView {
	+ {method} <color:red> post(self, request)
}

class BookSerializer {
	- name: string
    - category: string
    - author: string
    - publisher:string 
    - image_url:string
}

class BookFilter {
    - category_name
    - author_name
}

class BookManager {
	+ {method} <color:red> register_user(user): void
}

class BookModel {
}

ReactComponent <|-- BookClubListComponent
APIView <|-- ClubBookListAPIView
BookClubListComponent ..> ClubBookListAPIView
ClubBookListAPIView ..> BookSerializer
ClubBookListAPIView ..> BookManager
BookManager *-- BookModel
BookSerializer ..> BookFilter
@enduml
