# Generated by Django 4.2.1 on 2023-06-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_bookcopy_borrowing_user_delete_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('total_book', models.IntegerField()),
                ('comment', models.CharField(default=None, max_length=200)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.book')),
            ],
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='book_deposit_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='book_deposit_status',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='book_status',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('lost', 'Lost'), ('return', 'Return')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='number_phone',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.DeleteModel(
            name='Borrowing',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.user'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='book_copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.bookcopy'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.user'),
        ),
    ]
