# Generated by Django 4.2.2 on 2023-06-15 08:36

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('services', '0004_author_created_at_author_updated_at_book_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
