# Generated by Django 4.2.2 on 2023-06-16 14:20

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('services', '0006_member_address_member_birth_date_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
