# Generated by Django 4.2.2 on 2023-06-17 08:38

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('services', '0007_alter_member_address_alter_member_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberBookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('book_status', models.CharField(
                    choices=[('new', 'New'), ('used', 'Used'), ('lost', 'Lost'), ('return', 'Return'),
                             ('borrowed', 'Borrowed')], default='new', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField()),
                ('confirm_date', models.DateField()),
                ('order_status', models.CharField(
                    choices=[('draft', 'Draft'), ('Cancel', 'Cancel'), ('Created', 'Created'),
                             ('Confirmed', 'Confirmed'), ('Overdue', 'Overdue'), ('Completed', 'Completed')],
                    default='draft', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='leaved_at',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='MembershipOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(null=True)),
                ('overdue_day_count', models.IntegerField(null=True)),
                ('member_book_copy',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.memberbookcopy')),
                ('order',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_order_details',
                                   to='services.membershiporder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='membershiporder',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.membership'),
        ),
        migrations.AddField(
            model_name='memberbookcopy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.book'),
        ),
        migrations.AddField(
            model_name='memberbookcopy',
            name='current_reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='current_reader', to='services.membership'),
        ),
        migrations.AddField(
            model_name='memberbookcopy',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.membership'),
        ),
    ]
