# Generated by Django 4.2.2 on 2023-06-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_user_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
