# Generated by Django 4.2.2 on 2023-06-17 18:07

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('services', '0008_memberbookcopy_membershiporder_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiporder',
            name='confirm_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='membershiporder',
            name='order_date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='membershiporder',
            name='order_status',
            field=models.CharField(
                choices=[('draft', 'Draft'), ('Cancel', 'Cancel'), ('Created', 'Created'), ('Confirmed', 'Confirmed'),
                         ('Overdue', 'Overdue'), ('Completed', 'Completed')], default='Created', max_length=20),
        ),
    ]
