# Generated by Django 4.2.2 on 2023-06-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_membershiporder_confirm_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='leaved_at',
            field=models.DateField(default=None, null=True),
        ),
    ]
