# Generated by Django 4.2.2 on 2023-06-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_membership_leaved_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='number_phone',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='bookclub',
            name='address',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
