# Generated by Django 4.2.2 on 2023-06-18 09:41

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('services', '0011_rename_location_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='leaved_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
