# Generated by Django 4.2.2 on 2023-06-19 09:54

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('services', '0012_alter_membership_leaved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberbookcopy',
            name='book',
        ),
        migrations.AddField(
            model_name='memberbookcopy',
            name='book_copy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.bookcopy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='book_deposit_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='book_deposit_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='book_status',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('lost', 'Lost'), ('return', 'Return'),
                                            ('borrowed', 'Borrowed'), ('sharing_club', 'Sharing Club')], default='new',
                                   max_length=20),
        ),
    ]
