# Generated by Django 4.2.2 on 2023-06-22 16:39

from django.db import migrations, models
import services.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_bookcopy_book_deposit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=services.storage_backends.BaseStaticStorage(), upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
