# Generated by Django 4.2.2 on 2023-06-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_alter_bookcopy_book_deposit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='book_image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
