# Generated by Django 4.2.2 on 2023-06-23 03:33

from django.db import migrations, models

import services.storage_backends

class Migration(migrations.Migration):
    dependencies = [
        ('services', '0015_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default=None, null=True,
                                   storage=services.storage_backends.UserAvatarStorage(), upload_to='user_avatar/'),
        ),
    ]
