# Generated by Django 4.2.2 on 2023-06-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_bookcopy_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_card_photo',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
