# Generated by Django 4.2.2 on 2023-06-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_user_user_card_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_card_photo',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
