# Generated by Django 4.2.2 on 2023-06-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_alter_user_user_card_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_card_photo',
        ),
    ]
