# Generated by Django 4.2.2 on 2023-06-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
