# Generated by Django 4.2.2 on 2023-06-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_membership_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_status',
        ),
        migrations.AddField(
            model_name='membership',
            name='member_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('banned', 'Banned')], default='pending', max_length=10),
        ),
    ]
