# Generated by Django 4.2.2 on 2023-06-28 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_remove_memberbookcopy_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberbookcopy',
            name='in_club',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberbookcopy',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='BookCopyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('club_onboard', 'club_onboard')], max_length=50)),
                ('description', models.TextField()),
                ('attachments', models.ManyToManyField(to='services.uploadfile')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.bookcopy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
