# Generated by Django 4.2.2 on 2023-06-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_memberbookcopy_in_club_memberbookcopy_is_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberbookcopy',
            name='in_club',
        ),
        migrations.AddField(
            model_name='memberbookcopy',
            name='onboard_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
