# Generated by Django 4.2.2 on 2023-06-28 09:26

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('services', '0023_remove_memberbookcopy_in_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopyhistory',
            name='action',
            field=models.CharField(choices=[('donate_to_club', 'donate_to_club')], default='donate_to_club',
                                   max_length=50),
        ),
        migrations.AlterField(
            model_name='bookcopyhistory',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='services.uploadfile'),
        ),
    ]
