# Generated by Django 4.2.2 on 2023-07-02 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_remove_bookcopyhistory_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopyhistory',
            name='membership_borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.membership'),
        ),
        migrations.AlterField(
            model_name='bookcopyhistory',
            name='action',
            field=models.CharField(choices=[('donate_to_club', 'donate_to_club'), ('withdraw_book_from_club', 'withdraw_book_from_club'), ('club_borrow_book', 'club_borrow_book')], default='donate_to_club', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
