# Generated by Django 4.2.2 on 2023-07-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_bookcopyhistory_membership_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopyhistory',
            name='action',
            field=models.CharField(choices=[('donate_to_club', 'donate_to_club'), ('withdraw_book_from_club', 'withdraw_book_from_club'), ('club_borrow_book', 'club_borrow_book'), ('club_extend_due_date', 'club_extend_due_date')], default='donate_to_club', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookcopyhistory',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.uploadfile'),
        ),
        migrations.AlterField(
            model_name='bookcopyhistory',
            name='membership_borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.membership'),
        ),
    ]
