# Generated by Django 4.2.2 on 2023-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_alter_bookcopyhistory_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='book_deposit_price',
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='book_deposit_status',
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookcopyhistory',
            name='action',
            field=models.CharField(choices=[('donate_to_club', 'donate_to_club'), ('withdraw_book_from_club', 'withdraw_book_from_club'), ('club_borrow_book', 'club_borrow_book'), ('club_extend_due_date', 'club_extend_due_date'), ('club_return_book', 'club_return_book')], default='donate_to_club', max_length=50),
        ),
        migrations.AlterField(
            model_name='membershiporder',
            name='order_date',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membershiporderdetail',
            name='overdue_day_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membershiporderdetail',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
