# Generated by Django 4.2.2 on 2023-07-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_alter_member_address_alter_member_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='book_copy',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='book',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AlterField(
            model_name='membership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
