# Generated by Django 4.2.2 on 2023-07-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_remove_orderdetail_book_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
