# Generated by Django 4.2.3 on 2023-07-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_alter_book_author_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='follower',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
