# Generated by Django 4.2.3 on 2023-07-31 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_category_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('otp_code', models.CharField(max_length=6)),
                ('expiry_date', models.DateTimeField()),
                ('enable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'services_otp',
                'index_together': {('phone_number', 'enable')},
            },
        ),
    ]
