# Generated by Django 4.2.2 on 2023-07-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_remove_user_user_card_photo'),
        ('services', '0034_category_follower'),
    ]

    operations = [
    ]
