# Generated by Django 4.2.3 on 2023-07-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_user_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
