# Generated by Django 4.2.3 on 2023-08-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookclub',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
