# Generated by Django 4.2.2 on 2023-07-12 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0031_remove_orderdetail_book_copy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('init_count', models.IntegerField(blank=True, null=True)),
                ('current_count', models.IntegerField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.book')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.bookclub')),
            ],
            options={
                'db_table': 'dfree_book_tab',
            },
        ),
        migrations.CreateModel(
            name='DFreeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dfree_member_tab',
            },
        ),
        migrations.CreateModel(
            name='DFreeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_date', models.DateField()),
                ('due_date', models.DateField()),
                ('order_status', models.CharField(choices=[('created', 'Created'), ('overdue', 'Overdue'), ('complete', 'Complete')], default='created', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_free_book.dfreemember')),
            ],
            options={
                'db_table': 'dfree_order_tab',
            },
        ),
        migrations.CreateModel(
            name='DFreeOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('overdue_day_count', models.IntegerField(blank=True, null=True)),
                ('club_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_free_book.clubbook')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_free_book.dfreeorder')),
            ],
            options={
                'db_table': 'dfree_order_detail_tab',
            },
        ),
    ]
