# Generated by Django 4.2.2 on 2023-07-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_remove_orderdetail_book_copy_and_more'),
        ('d_free_book', '0002_dfreemember_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfreeorder',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.bookclub'),
        ),
    ]
