# Generated by Django 4.2.2 on 2023-07-12 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_remove_orderdetail_book_copy_and_more'),
        ('d_free_book', '0003_dfreeorder_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfreeorder',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.bookclub'),
        ),
    ]
