# Generated by Django 4.2.3 on 2023-07-16 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0004_alter_dfreeorder_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfreeorderdetail',
            name='book_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dfreeorderdetail',
            name='club_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='d_free_book.clubbook'),
        ),
    ]
