# Generated by Django 4.2.3 on 2023-07-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0005_dfreeorderdetail_book_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfreeorderdetail',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
