# Generated by Django 4.2.3 on 2023-07-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0006_dfreeorderdetail_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dfreeorder',
            name='order_status',
        ),
        migrations.AddField(
            model_name='dfreeorderdetail',
            name='order_status',
            field=models.CharField(choices=[('created', 'Created'), ('overdue', 'Overdue'), ('complete', 'Complete')], default='created', max_length=20),
        ),
    ]
