# Generated by Django 4.2.3 on 2023-07-16 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0033_alter_book_author_alter_book_category'),
        ('d_free_book', '0007_remove_dfreeorder_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfreemember',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.bookclub'),
        ),
    ]
