# Generated by Django 4.2.3 on 2023-07-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0008_dfreemember_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubbook',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
