# Generated by Django 4.2.3 on 2023-07-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_category_follower'),
        ('d_free_book', '0009_alter_clubbook_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfreeorder',
            name='creator_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.membership'),
        ),
        migrations.AddField(
            model_name='dfreeorderdetail',
            name='receiver_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.membership'),
        ),
    ]
