# Generated by Django 4.2.3 on 2023-07-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_category_follower'),
        ('d_free_book', '0011_rename_receiver_book_dfreeorderdetail_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfreemember',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='dfreemember',
            unique_together={('club', 'code')},
        ),
    ]
