# Generated by Django 4.2.3 on 2023-07-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0011_rename_receiver_book_dfreeorderdetail_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dfreeorderdetail',
            name='book_note',
        ),
    ]
