# Generated by Django 4.2.3 on 2023-07-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_category_follower'),
        ('d_free_book', '0012_alter_dfreemember_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dfreemember',
            unique_together={('club', 'phone_number'), ('club', 'code')},
        ),
    ]
