# Generated by Django 4.2.3 on 2023-07-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0013_remove_dfreeorderdetail_book_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfreeorder',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
