# Generated by Django 4.2.3 on 2023-07-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0013_remove_dfreeorderdetail_book_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfreemember',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
