# Generated by Django 4.2.3 on 2023-07-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0014_remove_dfreeorderdetail_book_note_dfreeorder_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFreeDraff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('order_date', models.DateField()),
                ('due_date', models.DateField()),
                ('club_book', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'dfree_draff_tab',
            },
        ),
        migrations.RemoveField(
            model_name='dfreeorder',
            name='address',
        ),
    ]
