# Generated by Django 4.2.3 on 2023-07-30 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_category_follower'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('d_free_book', '0014_dfreemember_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DFreeDraftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('order_date', models.DateField()),
                ('due_date', models.DateField()),
                ('club_books', models.CharField(max_length=50)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('draft_status', models.CharField(choices=[('created', 'created'), ('pending', 'pending')], default='pending', max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.bookclub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dfree_draft_order_tab',
            },
        ),
    ]
