# Generated by Django 4.2.3 on 2023-07-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0016_rename_dfreedraff_dfreedrafforder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfreedrafforder',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dfreedrafforder',
            name='club_books',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='dfreedrafforder',
            table='dfree_draff_order_tab',
        ),
    ]
