# Generated by Django 4.2.3 on 2023-08-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0016_dfreemember_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfreemember',
            name='first_order_date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
