# Generated by Django 4.2.3 on 2023-07-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0017_alter_dfreedrafforder_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfreedrafforder',
            name='draft_status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='dfreedrafforder',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
