# Generated by Django 4.2.3 on 2023-07-27 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0034_category_follower'),
        ('d_free_book', '0018_dfreedrafforder_draft_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfreedrafforder',
            name='book_club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='services.bookclub'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dfreedrafforder',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
