# Generated by Django 4.2.3 on 2023-07-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0019_dfreedrafforder_book_club_dfreedrafforder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dfreedrafforder',
            old_name='book_club',
            new_name='club',
        ),
    ]
