# Generated by Django 4.2.3 on 2023-07-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('d_free_book', '0020_rename_book_club_dfreedrafforder_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfreedrafforder',
            name='draft_status',
            field=models.CharField(choices=[('created', 'created'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
